### ISSUE TITLE
Add progress bar to Toast

### ISSUE THREAD

**Issue by mrpineapples** [mrpineapples/soundboard#15]
Code to get this working

```css
    &:after {
        animation: exitLeft calc(4.7 * 1s) linear forwards;
        background: rgba(255, 255, 255, 0.75);
        bottom: 0px;
        content: "";
        height: 5px;
        left: 0px;
        position: absolute;
        transform-origin: left center;
        width: 100%;
    }

    @keyframes exitLeft {
        to {
            transform: scaleX(0);
        }
    }
```
